### ISSUE TITLE
Anime pages layout on tablets. 

### ISSUE THREAD

**Issue by Felghana** [AnimeThemes/animethemes-web#120]
Currently the anime pages look like this on a 10.9 inch iPad. 
![082E0C7F-FD1A-493B-8732-D06657B2EA23](https://user-images.githubusercontent.com/1128514/166503397-958ef248-d7a6-44ef-8305-8ae5553e35de.jpeg)

The above is the same layout given to my iPhone. 

If you zoom out to 85% you get the desktop version (it has a slightly too small font though). 

![4F470574-1584-43A4-98A7-B096DA9BA86F](https://user-images.githubusercontent.com/1128514/166503429-f808b3b3-9ac3-4e09-9565-7b15eae9cefd.jpeg)

Is it possible for the websites settings to be adjusted so an tablet gets an similar layout to the second image? I think that would be more useful. 

(Clicked enter too earlyhence the edits).

**Comment by ManuelDevelopment** [comment]
Hey 👋 

I agree that filling up the whole screen with a cover image is not a good experience and that's something that bothers me about the mobile design since I first implemented it, but I haven't figured out a better solution yet. Of course we could just hide the cover image on mobile devices, but at least the anime page should have it in my opinion.

As for wanting the desktop layout on your tablet: Are you sure this isn't contradicting with your request from #99? Just want to make sure we are not changing this back and forth. I also want to keep the breakpoint for switching between an one column and two column design consistent across pages, so I rather not have an exception for the anime page here.

**Comment by Felghana** [comment]
> Hey 👋

Hi,

Thanks for the quick reply. 


> As for wanting the desktop layout on your tablet: Are you sure this isn’t contradicting with your request from #99? Just want to make sure we are not changing this back and forth

My issue in #99 was that the theme buttons were  overflowing which caused the layout to be  messed up hence the over truncation of the titles, as show below in the image from #99

![C0E7F91B-02F3-4A6F-B553-A839885198DA](https://user-images.githubusercontent.com/1128514/166902984-d4627942-1313-4781-b38b-9ab645f5c649.jpeg)

With all your improvements namely the fixed number of theme buttons and the drop down the two column layout actually works well on my iPad below show below (using zoom at 85% to get the two column version). 

The same page as above as it currently looks in the two column layout. 
![A80B3507-ED0C-4DDF-BE76-8E8489ED8D1D](https://user-images.githubusercontent.com/1128514/166903098-4aaa784e-94ba-4338-b0ba-7da9cabb425b.jpeg)

Two column layout with the drop down opened showing some of the longest titles

![CBD48625-0177-4CAF-A5C7-F959EFF7F6C4](https://user-images.githubusercontent.com/1128514/166903150-e02359f5-42ec-4d9d-875c-f8897f87bccc.jpeg)


> Of course we could just hide the cover image on mobile devices, but at least the anime page should have it in my opinion.

Now considering the one column layout, I agree the image is useful and should be included on the Anime page but not on the others like the series page. I can’t think  of a better way of displaying it though. 

> I also want to keep the breakpoint for switching between an one column and two column design consistent across pages

I agree that makes sense and is more consistent. 



One thing to note is that since the drop down to see all themes of an entry was added to the search page and the series page I rarely go the anime page so I am not sure what the best solution is here.

The only downside of the two column layout for the tablets is that there is less space for the title, but from the above image I think it shows enough to distinguish the entries.

**Comment by ManuelDevelopment** [comment]
Ok, I think I will just lower the breakpoint for switching to the one column layout, so you will have the two column layout without zooming out. Although this means I'm reverting part of #99, this should be ok, because of the fewer buttons on the cards.

Another idea that was suggested elsewhere is to remove the two buttons from the card entirely. Maybe that would make this a bit nicer too.

**Comment by Felghana** [comment]
> Ok, I think I will just lower the breakpoint for switching to the one column layout, so you will have the two column layout without zooming out. Although this means I'm reverting part of #99, this should be ok, because of the fewer buttons on the cards.

Great. 


> Another idea that was suggested elsewhere is to remove the two buttons from the card entirely. Maybe that would make this a bit nicer too.

Don’t have a strong option on this since the drop down was added, it easy enough to get to a first theme of an entry from the search page either way.

**Comment by Felghana** [comment]
I happened to look up a series and saw your nice new changes

![93EFAFBF-76EA-4AEA-A6AF-CD02318634E0](https://user-images.githubusercontent.com/1128514/167954983-39e2783c-d848-43f1-8c0d-ca763690731f.jpeg)
![FEF9EB09-4D06-4775-BF68-69E4FAD409EC](https://user-images.githubusercontent.com/1128514/167954991-95128dbd-e69e-4e02-b61e-5dbb0888c0ea.png)
![432A38F4-7809-4388-8576-0F40F8F9D8E1](https://user-images.githubusercontent.com/1128514/167954999-6798592b-a70b-4efe-83f9-1182446638e9.jpeg)
![A19A9AF5-E96D-4EC4-859F-0244DBA942BD](https://user-images.githubusercontent.com/1128514/167955003-24b196c8-68c3-4551-8fa5-9f4f1c987c66.jpeg)

**Comment by ManuelDevelopment** [comment]
I'm glad you like it ^^ Just pushed it with https://github.com/AnimeThemes/animethemes-web/commit/391a5cd9cba9ddf82fd7144c3c164a65e2127526. If this solves this issue, feel free to close it.

**Comment by Felghana** [comment]
Note you may want to change the boundary for the word wrapping of the song title in the drop down since in a rare edge case it can overflow by a few characters. 

![7A2140F3-07BA-4F50-806C-BB646BAA1D6E](https://user-images.githubusercontent.com/1128514/167956485-3fc4fefe-cd9d-4c26-8b96-b25f5f78a1d7.jpeg)

**Comment by ManuelDevelopment** [comment]
Good catch, thanks for the heads up 👍
