### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by ManuelDevelopment** [AnimeThemes/animethemes-web#13]
There should be a home page which highlights various parts of the page and an introduction to the service itself. There aren't really any plans for this page yet, so feel free to discuss possible contents in this issue.

**Comment by paranarimasu** [comment]
One component I'd like to see kept in some capacity are site announcements to drive attention to specific pages in the site, like in the first week of premieres for a new season, or externally from the site for an event like /r/Anime's Best OP/ED Contests.

**Comment by ManuelDevelopment** [comment]
I think this is done. Announcements are available as toasts and everything else has been implemented. I'm closing this.
