### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Uhhu738** [AnimeThemes/animethemes-web#139]
I can't play my locally saved playlist! I can't find a play button for it *anywhere*. Can one of the devs tell me how this works?

**Comment by along02** [comment]
Playing your playlist isn't an option yet. Playlists (https://github.com/AnimeThemes/animethemes-web/issues/9) are still in the works.

**Comment by Uhhu738** [comment]
> Playing your playlist isn't an option yet. Playlists (#9) are still in the works.

Oh okay
