### ISSUE TITLE
pro-solid-svg-icons hindered my use of this project

### ISSUE THREAD

**Issue by yu-yuxuan** [AnimeThemes/animethemes-web#146]
My system is macOS 12.5 with Apple silicon 

The package.json includes three fortawesome dependencies.
If I remove "@fortawesome/pro-solid-svg-icons": "^6.1.1", I will get error on `npm run dev`
If I keep it, I will get an error, which is
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@fortawesome%2fpro-solid-svg-icons - Not found
```
I search the website, the pro-solid-svg-icons is paid software.

I am wondering if there is any solution.

Thank you very much.

**Comment by ManuelDevelopment** [comment]
Hey, as you already noticed we are using the pro version of the icon library [Font Awesome](https://fontawesome.com/). This allows us to choose from a wider range of icons. To install the pro version you'd need a [license](https://fontawesome.com/plans).

Another solution would be to replace the package with the free version:

```diff
- "@fortawesome/pro-solid-svg-icons": "^6.1.1"
+ "@fortawesome/free-solid-svg-icons": "^6.1.1"
```

You can also use an alias, if you don't want to change all the imports:

```json
"@fortawesome/pro-solid-svg-icons": "npm:@fortawesome/free-solid-svg-icons@^6.1.1"
```

The unfortunate part is that you would need to replace or remove all the pro icons. If you run a build using `npm run build`, you will get error messages for the missing icons. The easiest solution would be to just replace the pro icons with free ones.

If you plan to contribute to this project, you can join our [Discord server](https://discordapp.com/invite/m9zbVyQ) so we can help you set the project up.

**Comment by yu-yuxuan** [comment]
@ManuelDevelopment Thank you very much. It is solved
