### ISSUE TITLE
Wrong Anime are displayed for the specific year index.

### ISSUE THREAD

**Issue by ponzis** [AnimeThemes/animethemes-web#25]
When looking at a specific year page anime appear in multiple seasons. When drilling down into a season page those anime disappear.

**To reproduce:**
Go to any page like
https://animethemes.github.io/animethemes-web/year/2020

**Expected outcome:**
Only anime for that season should be displayed.

**Actual outcome:**
Only the first three anime from the winter season are displayed.

**Comment by ManuelDevelopment** [comment]
This slipped through when converting to GraphQL queries. I'll assign myself and do it later.
