### ISSUE TITLE
Playlists

### ISSUE THREAD

**Issue by Maniload** [AnimeThemes/animethemes-web#9]
There should be playlists. Playlists can be created by users so they can save their favorite themes in a list. This probably needs some sort of profile system that we don't have yet.

**See also: https://github.com/AnimeThemes/animethemes-server/issues/226**

**Comment by omar-azmi** [comment]
Hi there, thanks for the playlist feature, it's pretty cool.
I just wanted to say that it would be nice to have a way to convert one's `Local Playlist` to a playlist tied to their account.

By the way, for anyone interested, I wrote a script that does that by clicking on the UI.
Here's the gist with instructions: [https://gist.github.com/omar-azmi/6e6b27c54249832fd7a1f7921219906c?permalink_comment_id=4999253#gistcomment-4999253](https://gist.github.com/omar-azmi/6e6b27c54249832fd7a1f7921219906c?permalink_comment_id=4999253#gistcomment-4999253)

**Comment by Maniload** [comment]
> Hi there, thanks for the playlist feature, it's pretty cool. I just wanted to say that it would be nice to have a way to convert one's `Local Playlist` to a playlist tied to their account.
> 
> By the way, for anyone interested, I wrote a script that does that by clicking on the UI. Here's the gist with instructions: https://gist.github.com/omar-azmi/6e6b27c54249832fd7a1f7921219906c?permalink_comment_id=4999253#gistcomment-4999253

Hey, thanks, I'm glad you like it. Unfortunately we won't provide an official way to convert local playlists into account-bound playlists. The effort wouldn't be worth it. Seeing that you already made your own solution this shouldn't be a big problem for you I assume ^^
